
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace nTier.Entity
{
	public abstract class _CustomerCustomerDemo : SqlClientEntity
	{
		public _CustomerCustomerDemo()
		{
			this.QuerySource = "CustomerCustomerDemo";
			this.MappingName = "CustomerCustomerDemo";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CustomerCustomerDemoLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(string CustomerID, string CustomerTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CustomerID, CustomerID);

parameters.Add(Parameters.CustomerTypeID, CustomerTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CustomerCustomerDemoLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CustomerID
			{
				get
				{
					return new SqlParameter("@CustomerID", SqlDbType.NChar, 5);
				}
			}
			
			public static SqlParameter CustomerTypeID
			{
				get
				{
					return new SqlParameter("@CustomerTypeID", SqlDbType.NChar, 10);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CustomerID = "CustomerID";
            public const string CustomerTypeID = "CustomerTypeID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CustomerID] = _CustomerCustomerDemo.PropertyNames.CustomerID;
					ht[CustomerTypeID] = _CustomerCustomerDemo.PropertyNames.CustomerTypeID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CustomerID = "CustomerID";
            public const string CustomerTypeID = "CustomerTypeID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CustomerID] = _CustomerCustomerDemo.ColumnNames.CustomerID;
					ht[CustomerTypeID] = _CustomerCustomerDemo.ColumnNames.CustomerTypeID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CustomerID = "s_CustomerID";
            public const string CustomerTypeID = "s_CustomerTypeID";

		}
		#endregion		
		
		#region Properties
	
		public virtual string CustomerID
	    {
			get
	        {
				return base.Getstring(ColumnNames.CustomerID);
			}
			set
	        {
				base.Setstring(ColumnNames.CustomerID, value);
			}
		}

		public virtual string CustomerTypeID
	    {
			get
	        {
				return base.Getstring(ColumnNames.CustomerTypeID);
			}
			set
	        {
				base.Setstring(ColumnNames.CustomerTypeID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CustomerID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CustomerID) ? string.Empty : base.GetstringAsString(ColumnNames.CustomerID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CustomerID);
				else
					this.CustomerID = base.SetstringAsString(ColumnNames.CustomerID, value);
			}
		}

		public virtual string s_CustomerTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CustomerTypeID) ? string.Empty : base.GetstringAsString(ColumnNames.CustomerTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CustomerTypeID);
				else
					this.CustomerTypeID = base.SetstringAsString(ColumnNames.CustomerTypeID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CustomerID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CustomerID, Parameters.CustomerID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CustomerTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CustomerTypeID, Parameters.CustomerTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CustomerID
		    {
				get
		        {
					if(_CustomerID_W == null)
	        	    {
						_CustomerID_W = TearOff.CustomerID;
					}
					return _CustomerID_W;
				}
			}

			public WhereParameter CustomerTypeID
		    {
				get
		        {
					if(_CustomerTypeID_W == null)
	        	    {
						_CustomerTypeID_W = TearOff.CustomerTypeID;
					}
					return _CustomerTypeID_W;
				}
			}

			private WhereParameter _CustomerID_W = null;
			private WhereParameter _CustomerTypeID_W = null;

			public void WhereClauseReset()
			{
				_CustomerID_W = null;
				_CustomerTypeID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CustomerID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CustomerID, Parameters.CustomerID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CustomerTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CustomerTypeID, Parameters.CustomerTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CustomerID
		    {
				get
		        {
					if(_CustomerID_W == null)
	        	    {
						_CustomerID_W = TearOff.CustomerID;
					}
					return _CustomerID_W;
				}
			}

			public AggregateParameter CustomerTypeID
		    {
				get
		        {
					if(_CustomerTypeID_W == null)
	        	    {
						_CustomerTypeID_W = TearOff.CustomerTypeID;
					}
					return _CustomerTypeID_W;
				}
			}

			private AggregateParameter _CustomerID_W = null;
			private AggregateParameter _CustomerTypeID_W = null;

			public void AggregateClauseReset()
			{
				_CustomerID_W = null;
				_CustomerTypeID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CustomerCustomerDemoInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CustomerCustomerDemoUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CustomerCustomerDemoDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CustomerID);
			p.SourceColumn = ColumnNames.CustomerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CustomerTypeID);
			p.SourceColumn = ColumnNames.CustomerTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CustomerID);
			p.SourceColumn = ColumnNames.CustomerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CustomerTypeID);
			p.SourceColumn = ColumnNames.CustomerTypeID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
