
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace nTier.Entity
{
	public abstract class _EmployeeTerritories : SqlClientEntity
	{
		public _EmployeeTerritories()
		{
			this.QuerySource = "EmployeeTerritories";
			this.MappingName = "EmployeeTerritories";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_EmployeeTerritoriesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int EmployeeID, string TerritoryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.EmployeeID, EmployeeID);

parameters.Add(Parameters.TerritoryID, TerritoryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_EmployeeTerritoriesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter EmployeeID
			{
				get
				{
					return new SqlParameter("@EmployeeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter TerritoryID
			{
				get
				{
					return new SqlParameter("@TerritoryID", SqlDbType.NVarChar, 20);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string EmployeeID = "EmployeeID";
            public const string TerritoryID = "TerritoryID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EmployeeID] = _EmployeeTerritories.PropertyNames.EmployeeID;
					ht[TerritoryID] = _EmployeeTerritories.PropertyNames.TerritoryID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string EmployeeID = "EmployeeID";
            public const string TerritoryID = "TerritoryID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EmployeeID] = _EmployeeTerritories.ColumnNames.EmployeeID;
					ht[TerritoryID] = _EmployeeTerritories.ColumnNames.TerritoryID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string EmployeeID = "s_EmployeeID";
            public const string TerritoryID = "s_TerritoryID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int? EmployeeID
	    {
			get
	        {
				return base.Getint(ColumnNames.EmployeeID);
			}
			set
	        {
				base.Setint(ColumnNames.EmployeeID, value);
			}
		}

		public virtual string TerritoryID
	    {
			get
	        {
				return base.Getstring(ColumnNames.TerritoryID);
			}
			set
	        {
				base.Setstring(ColumnNames.TerritoryID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_EmployeeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EmployeeID) ? string.Empty : base.GetintAsString(ColumnNames.EmployeeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmployeeID);
				else
					this.EmployeeID = base.SetintAsString(ColumnNames.EmployeeID, value);
			}
		}

		public virtual string s_TerritoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TerritoryID) ? string.Empty : base.GetstringAsString(ColumnNames.TerritoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TerritoryID);
				else
					this.TerritoryID = base.SetstringAsString(ColumnNames.TerritoryID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter EmployeeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EmployeeID, Parameters.EmployeeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TerritoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TerritoryID, Parameters.TerritoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter EmployeeID
		    {
				get
		        {
					if(_EmployeeID_W == null)
	        	    {
						_EmployeeID_W = TearOff.EmployeeID;
					}
					return _EmployeeID_W;
				}
			}

			public WhereParameter TerritoryID
		    {
				get
		        {
					if(_TerritoryID_W == null)
	        	    {
						_TerritoryID_W = TearOff.TerritoryID;
					}
					return _TerritoryID_W;
				}
			}

			private WhereParameter _EmployeeID_W = null;
			private WhereParameter _TerritoryID_W = null;

			public void WhereClauseReset()
			{
				_EmployeeID_W = null;
				_TerritoryID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter EmployeeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EmployeeID, Parameters.EmployeeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TerritoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TerritoryID, Parameters.TerritoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter EmployeeID
		    {
				get
		        {
					if(_EmployeeID_W == null)
	        	    {
						_EmployeeID_W = TearOff.EmployeeID;
					}
					return _EmployeeID_W;
				}
			}

			public AggregateParameter TerritoryID
		    {
				get
		        {
					if(_TerritoryID_W == null)
	        	    {
						_TerritoryID_W = TearOff.TerritoryID;
					}
					return _TerritoryID_W;
				}
			}

			private AggregateParameter _EmployeeID_W = null;
			private AggregateParameter _TerritoryID_W = null;

			public void AggregateClauseReset()
			{
				_EmployeeID_W = null;
				_TerritoryID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EmployeeTerritoriesInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EmployeeTerritoriesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EmployeeTerritoriesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.EmployeeID);
			p.SourceColumn = ColumnNames.EmployeeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TerritoryID);
			p.SourceColumn = ColumnNames.TerritoryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.EmployeeID);
			p.SourceColumn = ColumnNames.EmployeeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TerritoryID);
			p.SourceColumn = ColumnNames.TerritoryID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
