
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace nTier.Entity
{
	public abstract class _Region : SqlClientEntity
	{
		public _Region()
		{
			this.QuerySource = "Region";
			this.MappingName = "Region";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RegionLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int RegionID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.RegionID, RegionID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_RegionLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter RegionID
			{
				get
				{
					return new SqlParameter("@RegionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter RegionDescription
			{
				get
				{
					return new SqlParameter("@RegionDescription", SqlDbType.NChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string RegionID = "RegionID";
            public const string RegionDescription = "RegionDescription";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RegionID] = _Region.PropertyNames.RegionID;
					ht[RegionDescription] = _Region.PropertyNames.RegionDescription;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string RegionID = "RegionID";
            public const string RegionDescription = "RegionDescription";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RegionID] = _Region.ColumnNames.RegionID;
					ht[RegionDescription] = _Region.ColumnNames.RegionDescription;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string RegionID = "s_RegionID";
            public const string RegionDescription = "s_RegionDescription";

		}
		#endregion		
		
		#region Properties
	
		public virtual int? RegionID
	    {
			get
	        {
				return base.Getint(ColumnNames.RegionID);
			}
			set
	        {
				base.Setint(ColumnNames.RegionID, value);
			}
		}

		public virtual string RegionDescription
	    {
			get
	        {
				return base.Getstring(ColumnNames.RegionDescription);
			}
			set
	        {
				base.Setstring(ColumnNames.RegionDescription, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_RegionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RegionID) ? string.Empty : base.GetintAsString(ColumnNames.RegionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RegionID);
				else
					this.RegionID = base.SetintAsString(ColumnNames.RegionID, value);
			}
		}

		public virtual string s_RegionDescription
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RegionDescription) ? string.Empty : base.GetstringAsString(ColumnNames.RegionDescription);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RegionDescription);
				else
					this.RegionDescription = base.SetstringAsString(ColumnNames.RegionDescription, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter RegionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RegionID, Parameters.RegionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RegionDescription
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RegionDescription, Parameters.RegionDescription);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter RegionID
		    {
				get
		        {
					if(_RegionID_W == null)
	        	    {
						_RegionID_W = TearOff.RegionID;
					}
					return _RegionID_W;
				}
			}

			public WhereParameter RegionDescription
		    {
				get
		        {
					if(_RegionDescription_W == null)
	        	    {
						_RegionDescription_W = TearOff.RegionDescription;
					}
					return _RegionDescription_W;
				}
			}

			private WhereParameter _RegionID_W = null;
			private WhereParameter _RegionDescription_W = null;

			public void WhereClauseReset()
			{
				_RegionID_W = null;
				_RegionDescription_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter RegionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RegionID, Parameters.RegionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RegionDescription
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RegionDescription, Parameters.RegionDescription);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter RegionID
		    {
				get
		        {
					if(_RegionID_W == null)
	        	    {
						_RegionID_W = TearOff.RegionID;
					}
					return _RegionID_W;
				}
			}

			public AggregateParameter RegionDescription
		    {
				get
		        {
					if(_RegionDescription_W == null)
	        	    {
						_RegionDescription_W = TearOff.RegionDescription;
					}
					return _RegionDescription_W;
				}
			}

			private AggregateParameter _RegionID_W = null;
			private AggregateParameter _RegionDescription_W = null;

			public void AggregateClauseReset()
			{
				_RegionID_W = null;
				_RegionDescription_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RegionInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RegionUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_RegionDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.RegionID);
			p.SourceColumn = ColumnNames.RegionID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.RegionID);
			p.SourceColumn = ColumnNames.RegionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RegionDescription);
			p.SourceColumn = ColumnNames.RegionDescription;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
