
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace nTier.Entity
{
	public class CustomerDemographics : _CustomerDemographics
	{
		public CustomerDemographics()
		{
		
		}
	}
}
